-- Tracking import Excel + metadata contract
ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "status_import" VARCHAR(20) DEFAULT 'incomplet';
ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "campuri_lipsa" JSONB DEFAULT NULL;
ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "sursa_foaie" VARCHAR(100) DEFAULT NULL;
ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "nr_crt_excel" INTEGER DEFAULT NULL;
ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "bsn" VARCHAR(50) DEFAULT NULL;
ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "posted_w" VARCHAR(50) DEFAULT NULL;
ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "a1" VARCHAR(50) DEFAULT NULL;
ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "decizie" VARCHAR(50) DEFAULT NULL;
ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "fisa_app_psi" VARCHAR(50) DEFAULT NULL;
ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "data_angajare_originala" DATE DEFAULT NULL;
ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "data_incetare_originala" VARCHAR(50) DEFAULT NULL;
